- name: Check if target variable is in accepted ones
  set_fact:
    ubuntu_target: "{{ target in ['ubuntu_22_04', 'ubuntu_20_04'] }}"

- name: Download AWS ZIP
  shell: |
    rm -rf awscliv2.zip aws
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  when: ubuntu_target

- name: Unzip download
  shell: |
    unzip awscliv2.zip
    rm -rf awscliv2.zip
  when: ubuntu_target

- name: Install with downloaded script
  shell: |
    ./aws/install
  become: true
  when: ubuntu_target and awsExists.stat.exists

- name: Update with downloaded script
  shell: |
    ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
  become: true
  when: ubuntu_target and not awsExists.stat.exists
