- name: Check if target variable is in accepted ones
  set_fact:
    ubuntu_target: "{{ target in ['ubuntu_22_04', 'ubuntu_20_04', 'ubuntu_23_10'] }}"

- name: Install Python3
  apt:
    name: "python{{ bastion.utils.python.version }}"
    state: present
  become: true
  when: ubuntu_target

- name: Install pip
  apt:
    name: python3-pip
    state: present
  become: true
  when: ubuntu_target

- name: Upgrade pip
  shell: |
    python3 -m pip install --upgrade pip
    when: ubuntu_target

- name: Install pipenv
  shell: |
    sudo -H pip3 install pipenv
  become: true
  when: ubuntu_target
